# Generated by Django 4.2.6 on 2023-10-10 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0013_alter_productos_id_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='hora_baja',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productos',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
