# Generated by Django 4.2.6 on 2023-10-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0014_productos_hora_baja_productos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
