# Generated by Django 4.2.6 on 2023-10-10 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0015_productos_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='hora_baja',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
