# Generated by Django 4.2.6 on 2023-10-11 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0017_productos_usernamere'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha_edit',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
