# Generated by Django 4.2.6 on 2023-10-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0019_productos_useredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='movimiento',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
